# https://www.syncano.io/blog/configuring-running-django-celery-docker-containers-pt-1/

version: '2'

services:  

  # PostgreSQL database

  db:
    image: kartoza/postgis:9.5-2.2
    hostname: db
    environment:
      - POSTGRES_USER=geoapi
      - POSTGRES_PASSWORD=likes_geography
      - POSTGRES_DB=geoapi
    ports:
      - "25432:5432"
    volumes_from:
      - data

  data:
    restart: always
    image: kartoza/postgis:9.5-2.2
    volumes:
      - /var/lib/postgresql
    command: "true"

  # Flask web server
  web:
    build: ./web
    hostname: web
    volumes:
      - .:/usr/src/app  # mount current directory inside container
    ports:
      - "8000:5000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - db
    depends_on:
      - db