# https://nickjanetakis.com/blog/dockerize-a-flask-celery-and-redis-application-with-docker-compose  
# https://dzone.com/articles/how-ansible-and-docker-fit  
  
FROM python:2.7.13-onbuild  
  
MAINTAINER Dheeraj Chand <dheeraj@mautinoa.com>  
  
RUN apt-get update && apt-get install -y \
    vim \
    nano \
    apt-file \
    python-setuptools \
    python-pip \
    virtualenvwrapper \
    supervisor \
    python-apt \
    python-pycurl \
    libpq-dev \
    python-psycopg2 \
    git \
    gdal-bin

  
  
  
